# name of the model, will be used as the folder to store the model in
name: modelname

# dataset to train on
dataset: mnist

# dataset args, we're defining additional ways we want to load mnist
# in this case we're defining what techniques we want to use to expand the training data
# rotation is the max value to rotate images by in either direction, which is randomly taken
# rot per sample times and appended to the dataset
dataset_args:
  rotation: 15
  rot_per_sample: 5

# weight initilization technique to use
weight: he

layers:
  # input layers are special and don't require the number of nodes to be
  # explicitly stated, that can vary based on dataset args and will be set
  # at runtime, it does need to be stated however, as options like
  # batch reg, etc, would be applicable to the input layer
  - type: input

  # a hidden layer has many different options for configuration, some of which are shown below
  # most configs are optional, like dropout, and update
  # type, nodes, and activation are required however
  # most values come with a default, like l1 and l2 lambda, making setting there values not necessary, but
  # can be a good assurance of sanity
  - type: hidden
    nodes: 128
    dropout: 0.3
    activation: leakyrelu
    regularization: l1
    l1_lambda: 0.0001

  - type: hidden
    nodes: 128
    dropout: 0.3
    activation: leakyrelu
    regularization: l2
    l2_lambda: 0.0002

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy

# number of epochs to train for
epochs: 1000

# how often to test the model against the validation/test dataset in epochs
valid_freq: 1

# learning rate to use during model training
learning_rate: 0.05

# batch size to use for training
batch_size: 512