name: basicmnist
dataset: mnist


layers:
  - type: input

  - type: hidden
    nodes: 256
    momentum: 0.9
    activation: leakyrelu

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy
    momentum: 0.9


weight: he
epochs: 100
valid_freq: 1
learning_rate: 0.005
batch_size: 512