name: basicmnist
dataset: mnist

dataset_args:
  running_augmentations: true

  rotation: 15
  min_rotation: 10
  rot_variants: 2

  elastic_deform:
    alpha: 34
    sigma: 4
    variants: 1

optimizer:
  type: sgd
  learning_rate: 0.01

layers:
  - type: input

  - type: hidden
    nodes: 256
    dropout: 0.2
    activation: leakyrelu

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy

seed: 42

weight: he
epochs: 100
valid_freq: 1
batch_size: 512
