name: basicfmnist
dataset: fmnist

dataset_args:
  rotation: 15
  min_rotation: 10
  rot_variants: 5

optimizer:
  type: adam
  learning_rate: 0.1

layers:
  - type: input

  - type: hidden
    nodes: 512
    dropout: 0.3
    activation: leakyrelu

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy

weight: he
epochs: 100
valid_freq: 1
batch_size: 512
