name: basicmnist
dataset: mnist

optimizer:
  type: adam
  learning_rate: 0.05

layers:
  - type: input

  - type: hidden
    nodes: 256
    activation: leakyrelu

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy


weight: he
epochs: 1000
valid_freq: 1
batch_size: 512
