name: basicmnist
dataset: mnist


optimizer:
  type: adam
  learning_rate: 0.001

layers:
  - type: input

  - type: hidden
    nodes: 256
    dropout: 0.2
    activation: leakyrelu

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy

seed: 42

weight: he
epochs: 500
valid_freq: 1
batch_size: 512
