name: basicmnist
dataset: mnist

weight: he

layers:
  - type: input

  - type: hidden
    nodes: 784
    dropout: 0.3
    activation: leakyrelu

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy

epochs: 1000
valid_freq: 1
learning_rate: 0.05
batch_size: 512