name: bestmnist
dataset: mnist

dataset_args:
  running_augmentations: true

  rotation: 15
  min_rotation: 10
  rot_variants: 4

  scale: 0.1
  min_scale: 0.15
  scale_variants: 2

  shear: 0.2
  min_shear: 0.1
  shear_variants: 4
  
  elastic_deform:
    alpha: 34
    sigma: 4
    variants: 5

optimizer:
  type: adam
  learning_rate: 0.01


layers:
  - type: input

  - type: hidden
    dropout: 0.3
    nodes: 1024
    activation: leakyrelu

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy

seed: 406246

weight: he
epochs: 1000
valid_freq: 1
batch_size: 512
