name: bestmnist
dataset: mnist

dataset_args:
  rotation: 15
  rot_per_sample: 8

weight: he

layers:
  - type: input

  - type: hidden
    nodes: 784
    dropout: 0.2
    activation: leakyrelu

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy
    momentum: 0.1

epochs: 1000
valid_freq: 1
learning_rate: 0.001
batch_size: 512