name: bestmnist
dataset: mnist

dataset_args:
  rotation: 15
  min_rotation: 8
  rot_variants: 8
  scale: 0.1
  min_scale: 0.1
  scale_variants: 2


optimizer:
  type: adam
  learning_rate: 0.01


layers:
  - type: input

  - type: hidden
    dropout: 0.3
    nodes: 1024
    activation: leakyrelu

  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy

weight: he
epochs: 1000
valid_freq: 1
batch_size: 512
