name: biggestmandle
dataset: mandlebrot

optimizer:
  type: adam
  learning_rate: 0.0005

dataset_args:
  samples: 200000
  mandledepth: 1000
  fourier_series: 256

weight: he

layers:
  - type: input


  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
  
  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu

  - type: hidden
    nodes: 512
    activation: leakyrelu
    skipconn: 0


  - type: output
    nodes: 1
    activation: sigmoid
    loss: mse
    metric: mae

seed: 2377336722
epochs: 10000
valid_freq: 1
batch_size: 512
