name: bigmandle
dataset: mandlebrot

optimizer:
  type: adam
  learning_rate: 0.005

dataset_args:
  samples: 200000
  mandledepth: 1000
  fourier_series: 64

weight: he

layers:
  - type: input


  - type: hidden
    nodes: 1024
    activation: leakyrelu

  - type: hidden
    nodes: 1024
    activation: leakyrelu

  - type: hidden
    nodes: 1024
    activation: leakyrelu

  - type: hidden
    nodes: 1024
    activation: leakyrelu

  - type: hidden
    nodes: 1024
    activation: leakyrelu


  - type: output
    nodes: 1
    activation: sigmoid
    loss: mse
    metric: mae

epochs: 10000
valid_freq: 1
batch_size: 1024
