name: smallmnist
dataset: mnist

dataset_args:
  rotation: 15
  rot_variants: 5

optimizer:
  type: sgd
  learning_rate: 0.01

weight: normalize

layers:
  - type: input

  - type: hidden
    nodes: 32
    activation: leakyrelu


  - type: hidden
    nodes: 32
    activation: leakyrelu


  - type: output
    nodes: 10
    activation: sigmoid
    loss: onehot
    metric: accuracy

epochs: 500
valid_freq: 1
batch_size: 512