name: tallmandle
dataset: mandlebrot

dataset_args:
  samples: 500000
  mandledepth: 1000
  fourier_series: 32

optimizer:
  type: adam
  learning_rate: 0.005


layers:
  - type: input

  - type: hidden
    nodes: 2048
    dropout: 0.2
    activation: leakyrelu

  - type: output
    nodes: 1
    activation: sigmoid
    loss: mse
    metric: mae

seed: 13754265
weight: he
epochs: 10000
valid_freq: 1
batch_size: 2048
